# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0006_auto_20161012_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not Important', 'Not Important')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not Important', 'Not Important')], max_length=50),
        ),
    ]
